build:
  image: latest

python:
  version: 3.6
  pip_install: true
  use_system_site_packages: true

requirements_file: docs/sphinx-requirements.txt

formats: []  # Disable htmlzip, pdf and epub builds to save resources
