version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - requirements: docs/sphinx-requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py
